### ISSUE TITLE
Needs to keep track of purchases and sales

### ISSUE THREAD

**Issue by jefhar** [CyberPunkMetalHead/bitcoin-bot-buy-if-elon-tweets#1]
As the IRS requires gains taxes on every bit coin purchased, this needs a record of exactly which coins are purchases, sales, the dates, and values for your tax accountant.

https://www.irs.gov/businesses/small-businesses-self-employed/virtual-currencies

**Comment by CyberPunkMetalHead** [comment]
Hi @jefhar - the bot is integrated with trading platform MetaTrader5, which by default keeps track of all account activity.
